"""Synthetic data generator for Clinetics.

ALL DATA PRODUCED BY THIS SCRIPT IS SYNTHETIC. No real patient data is used,
read, or derived from. Names and contact details come from Faker; every
clinically meaningful distribution is generated by the explicit models below.

The point of this file is that the data must contain *genuinely learnable
structure*. Random noise would let the ML layer report metrics without those
metrics meaning anything. Every distribution below is therefore specified,
parameterised, and — critically — verified afterwards by
`scripts/validate_data.py`, which fails if the intended correlations are not
actually present in the generated rows.

================================================================================
1. NO-SHOW MODEL
================================================================================
A no-show is generated from a logistic model, not an i.i.d. coin flip:

    logit(p) = B0
             + B_LEAD     * log1p(lead_time_days)
             + B_DOW[weekday]
             + B_HOUR(hour_of_day)
             + patient_latent_offset
             + B_NEW_PATIENT * is_new_patient
             + B_URGENCY[urgency]

    B0                = -2.30   (baseline ~9% before any adjustment)
    B_LEAD            = +0.42   per unit log1p(days). Longer lead time means a
                                higher no-show rate, and the log makes the
                                effect saturate: days 0->7 matter far more than
                                days 30->37. This is the single strongest
                                predictor and the primary thing Phase 3 must
                                recover.
    B_DOW             = Mon +0.30, Tue -0.05, Wed -0.10, Thu 0.00,
                        Fri +0.22, Sat +0.15, Sun +0.10
                                Monday and Friday are worse, matching the
                                well-known start/end-of-week pattern.
    B_HOUR            = +0.34 at 08:00, falling to -0.12 around 12:00, rising
                        to +0.40 by 18:00 (piecewise linear via _hour_effect).
                                Early and late slots are missed more often.
    patient_latent    = logit(Beta(2.0, 8.0)) - logit(0.2), i.e. a per-patient
                        offset with mean ~0. Each patient carries a stable
                        propensity, so a patient's OWN HISTORY predicts their
                        future behaviour. Without this the "patient historical
                        no-show rate" feature would be pure noise.
    B_NEW_PATIENT     = +0.45   First-time patients are less committed.
    B_URGENCY         = routine 0.0, urgent -0.70, emergency -1.40
                                Sicker patients turn up.

Target aggregate no-show rate: 15-22%.

================================================================================
2. DEMAND MODEL
================================================================================
Appointment volume per (date, specialty, hour) is Poisson:

    lambda = BASE_DAILY[specialty]
           * WEEKDAY_MULT[weekday]
           * HOUR_PROFILE[specialty][hour]
           * (1 + SEASONAL_AMPLITUDE * sin(2*pi*(day_of_year - 20)/365))

    BASE_DAILY        cardiology 7.0, dermatology 6.0, general_practice 14.0,
                      orthopedics 5.5, pediatrics 8.0
    WEEKDAY_MULT      Mon 1.35, Tue 1.05, Wed 1.00, Thu 1.02, Fri 0.95,
                      Sat 0.45, Sun 0.10
                                Strong weekday/weekend split, with Monday the
                                busiest day.
    HOUR_PROFILE      per specialty, normalised over clinic hours:
                        * general_practice / cardiology / orthopedics:
                          morning-weighted, peaking 09:00-11:00
                        * dermatology: EVENING-weighted, peaking 16:00-18:00
                        * pediatrics: bimodal, peaking 09:00 and 15:00-16:00
                                Specialty-specific intra-day shape is what makes
                                an hourly forecast worth training at all.
    SEASONAL_AMPLITUDE = 0.15, annual sinusoid peaking in late winter.

================================================================================
3. DURATION MODEL
================================================================================
    duration = clip(round_to_5(LogNormal(mu=log(base), sigma=SIGMA)
                               + NEW_PATIENT_EXTRA * is_new_patient),
                    10, 120)

    base (minutes)    cardiology 35, dermatology 20, general_practice 15,
                      orthopedics 30, pediatrics 25
    SIGMA             0.28  (log-scale); right-skewed, as real consultations are
    NEW_PATIENT_EXTRA 8 minutes

================================================================================
4. LEAD TIME MODEL
================================================================================
    routine    lead ~ Gamma(shape=2.0, scale=7.0), clipped to [0, 90]
    urgent     lead ~ Gamma(shape=1.2, scale=2.0), clipped to [0, 14]
    emergency  lead = 0 with p=0.7, else Gamma(1.0, 1.0) clipped to [0, 3]

Urgency mix: routine 0.80, urgent 0.16, emergency 0.04.

================================================================================
5. CANCELLATION MODEL
================================================================================
Cancellation is decided BEFORE no-show (a cancelled appointment cannot also be
a no-show), and shares the lead-time driver:

    logit(p_cancel) = -2.60 + 0.30 * log1p(lead_time_days)

================================================================================
USAGE
================================================================================
    uv run python scripts/generate_data.py --months 12 --doctors 8 --patients 1500
    uv run python scripts/validate_data.py        # the gate; must pass next

`--reset` truncates all generated rows first. The script is deterministic for a
given `--seed`.
"""

from __future__ import annotations

import argparse
import datetime as dt
import logging
import math
import random
import sys
from dataclasses import dataclass, field

from faker import Faker
from sqlalchemy import create_engine, insert, select, text
from sqlalchemy.orm import Session

sys.path.insert(0, str(__import__("pathlib").Path(__file__).resolve().parent.parent))

from app.core.config import settings
from app.models import (
    Appointment,
    AppointmentStatus,
    Availability,
    Clinic,
    Doctor,
    Patient,
    Room,
    Specialty,
    Urgency,
    Weekday,
    doctor_specialty,
)

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger("generate_data")

# ---------------------------------------------------------------------------
# Parameters (every value here is documented in the module docstring above)
# ---------------------------------------------------------------------------
CLINIC_OPEN_HOUR = 8
CLINIC_CLOSE_HOUR = 19  # exclusive; last appointment starts before this
SLOT_MINUTES = 15

B0_NO_SHOW = -2.30
B_LEAD = 0.42
B_NEW_PATIENT = 0.45
B_DOW: dict[int, float] = {1: 0.30, 2: -0.05, 3: -0.10, 4: 0.00, 5: 0.22, 6: 0.15, 7: 0.10}
B_URGENCY: dict[Urgency, float] = {
    Urgency.ROUTINE: 0.0,
    Urgency.URGENT: -0.70,
    Urgency.EMERGENCY: -1.40,
}
PATIENT_PROPENSITY_ALPHA = 2.0
PATIENT_PROPENSITY_BETA = 8.0
PATIENT_PROPENSITY_MEAN = PATIENT_PROPENSITY_ALPHA / (
    PATIENT_PROPENSITY_ALPHA + PATIENT_PROPENSITY_BETA
)

B0_CANCEL = -2.60
B_LEAD_CANCEL = 0.30

WEEKDAY_MULT: dict[int, float] = {1: 1.35, 2: 1.05, 3: 1.00, 4: 1.02, 5: 0.95, 6: 0.45, 7: 0.10}
SEASONAL_AMPLITUDE = 0.15

URGENCY_MIX: list[tuple[Urgency, float]] = [
    (Urgency.ROUTINE, 0.80),
    (Urgency.URGENT, 0.16),
    (Urgency.EMERGENCY, 0.04),
]

NEW_PATIENT_EXTRA_MINUTES = 8
DURATION_SIGMA = 0.28


@dataclass(frozen=True)
class SpecialtySpec:
    name: str
    slug: str
    base_duration: int
    base_daily_volume: float
    # Relative weight per clock hour; normalised at use.
    hour_weights: dict[int, float] = field(default_factory=dict)


def _morning_weighted() -> dict[int, float]:
    """Peaks 09:00-11:00, tapering through the afternoon."""
    return {h: max(0.05, 1.6 - 0.11 * (h - 9) ** 2 * 0.35) for h in range(8, 19)}


def _evening_weighted() -> dict[int, float]:
    """Dermatology: patients come after work. Peaks 16:00-18:00."""
    return {h: max(0.05, 0.35 + 0.14 * (h - 8)) for h in range(8, 19)}


def _bimodal() -> dict[int, float]:
    """Paediatrics: a morning peak and an after-school peak."""
    out = {}
    for h in range(8, 19):
        morning = math.exp(-((h - 9.5) ** 2) / 2.2)
        afternoon = math.exp(-((h - 15.5) ** 2) / 2.6)
        out[h] = 0.15 + morning + 0.9 * afternoon
    return out


SPECIALTIES: list[SpecialtySpec] = [
    SpecialtySpec("Cardiology", "cardiology", 35, 7.0, _morning_weighted()),
    SpecialtySpec("Dermatology", "dermatology", 20, 6.0, _evening_weighted()),
    SpecialtySpec("General Practice", "general-practice", 15, 14.0, _morning_weighted()),
    SpecialtySpec("Orthopedics", "orthopedics", 30, 5.5, _morning_weighted()),
    SpecialtySpec("Pediatrics", "pediatrics", 25, 8.0, _bimodal()),
]


# ---------------------------------------------------------------------------
# Model functions
# ---------------------------------------------------------------------------
def _logit(p: float) -> float:
    return math.log(p / (1.0 - p))


def _sigmoid(x: float) -> float:
    return 1.0 / (1.0 + math.exp(-x))


def _hour_effect(hour: int) -> float:
    """Piecewise-linear no-show effect by hour: high early, dip midday, high late."""
    if hour <= 12:
        # 08:00 -> +0.34 down to 12:00 -> -0.12
        return 0.34 + (hour - 8) * (-0.46 / 4.0)
    # 12:00 -> -0.12 up to 18:00 -> +0.40
    return -0.12 + (hour - 12) * (0.52 / 6.0)


def no_show_probability(
    *,
    lead_days: int,
    weekday: int,
    hour: int,
    patient_offset: float,
    is_new_patient: bool,
    urgency: Urgency,
) -> float:
    logit_p = (
        B0_NO_SHOW
        + B_LEAD * math.log1p(lead_days)
        + B_DOW[weekday]
        + _hour_effect(hour)
        + patient_offset
        + B_NEW_PATIENT * float(is_new_patient)
        + B_URGENCY[urgency]
    )
    return _sigmoid(logit_p)


def cancel_probability(lead_days: int) -> float:
    return _sigmoid(B0_CANCEL + B_LEAD_CANCEL * math.log1p(lead_days))


def sample_lead_days(rng: random.Random, urgency: Urgency) -> int:
    if urgency is Urgency.EMERGENCY:
        if rng.random() < 0.7:
            return 0
        return min(3, int(rng.gammavariate(1.0, 1.0)))
    if urgency is Urgency.URGENT:
        return min(14, int(rng.gammavariate(1.2, 2.0)))
    return min(90, int(rng.gammavariate(2.0, 7.0)))


def sample_duration(rng: random.Random, spec: SpecialtySpec, is_new_patient: bool) -> int:
    raw = rng.lognormvariate(math.log(spec.base_duration), DURATION_SIGMA)
    if is_new_patient:
        raw += NEW_PATIENT_EXTRA_MINUTES
    return int(max(10, min(120, round(raw / 5.0) * 5)))


def sample_urgency(rng: random.Random) -> Urgency:
    r = rng.random()
    cumulative = 0.0
    for urgency, weight in URGENCY_MIX:
        cumulative += weight
        if r < cumulative:
            return urgency
    return Urgency.ROUTINE


def seasonal_factor(date: dt.date) -> float:
    return 1.0 + SEASONAL_AMPLITUDE * math.sin(2 * math.pi * (date.timetuple().tm_yday - 20) / 365)


def expected_volume(spec: SpecialtySpec, date: dt.date, hour: int) -> float:
    weights = spec.hour_weights
    total = sum(weights.values())
    share = weights.get(hour, 0.0) / total if total else 0.0
    return spec.base_daily_volume * WEEKDAY_MULT[date.isoweekday()] * share * seasonal_factor(date)


# ---------------------------------------------------------------------------
# Slot bookkeeping — the exclusion constraint is real, so the generator must
# not attempt to double-book. Placement is explicit rather than hopeful.
# ---------------------------------------------------------------------------
class DoctorCalendar:
    """Tracks which 15-minute slots a doctor has taken on each date."""

    def __init__(self) -> None:
        self._taken: dict[tuple[int, dt.date], set[int]] = {}

    @staticmethod
    def _slot_index(t: dt.time) -> int:
        return (t.hour * 60 + t.minute) // SLOT_MINUTES

    def try_book(self, doctor_id: int, date: dt.date, start: dt.time, duration: int) -> bool:
        first = self._slot_index(start)
        n_slots = math.ceil(duration / SLOT_MINUTES)
        end_minutes = first * SLOT_MINUTES + n_slots * SLOT_MINUTES
        if end_minutes > CLINIC_CLOSE_HOUR * 60:
            return False
        key = (doctor_id, date)
        taken = self._taken.setdefault(key, set())
        wanted = set(range(first, first + n_slots))
        if wanted & taken:
            return False
        taken |= wanted
        return True


# ---------------------------------------------------------------------------
# Generation
# ---------------------------------------------------------------------------
def reset_data(session: Session) -> None:
    log.info("truncating existing generated data")
    session.execute(
        text(
            "TRUNCATE analytics.schedule_entry, analytics.schedule, analytics.forecast, "
            "analytics.doctor_utilization, appointment, availability, doctor_specialty, "
            "room, doctor, patient, specialty, clinic, user_account RESTART IDENTITY CASCADE"
        )
    )
    session.commit()


def seed_reference_data(
    session: Session, fake: Faker, rng: random.Random, n_doctors: int
) -> tuple[Clinic, dict[str, Specialty], list[Doctor]]:
    clinic = Clinic(
        name="Clinetics Central",
        opens_at=dt.time(CLINIC_OPEN_HOUR, 0),
        closes_at=dt.time(CLINIC_CLOSE_HOUR, 0),
        timezone="UTC",
        address=fake.street_address(),
        phone=fake.phone_number()[:32],
    )
    session.add(clinic)
    session.flush()

    specialties: dict[str, Specialty] = {}
    for spec in SPECIALTIES:
        row = Specialty(
            name=spec.name,
            slug=spec.slug,
            default_duration_minutes=spec.base_duration,
            description=f"{spec.name} outpatient services",
        )
        session.add(row)
        session.flush()
        specialties[spec.slug] = row

    for i in range(1, 7):
        session.add(Room(clinic_id=clinic.id, name=f"Room {i}", capacity=1))

    # Distribute doctors across specialties, weighted by demand so the busiest
    # specialty has the most capacity. Without this the generator would produce
    # a schedule that is structurally impossible to satisfy.
    weights = [s.base_daily_volume for s in SPECIALTIES]
    doctors: list[Doctor] = []
    for i in range(n_doctors):
        primary = rng.choices(SPECIALTIES, weights=weights, k=1)[0]
        doctor = Doctor(
            clinic_id=clinic.id,
            first_name=fake.first_name(),
            last_name=fake.last_name(),
            license_number=f"LIC-{100000 + i}",
            is_active=True,
        )
        session.add(doctor)
        session.flush()
        session.execute(
            insert(doctor_specialty).values(
                doctor_id=doctor.id,
                specialty_id=specialties[primary.slug].id,
                is_primary=True,
            )
        )
        # ~35% of doctors hold a second, non-primary specialty. This is what
        # makes the many-to-many junction carry real information rather than
        # being a one-row-per-doctor table in disguise.
        if rng.random() < 0.35:
            other = rng.choice([s for s in SPECIALTIES if s.slug != primary.slug])
            session.execute(
                insert(doctor_specialty).values(
                    doctor_id=doctor.id,
                    specialty_id=specialties[other.slug].id,
                    is_primary=False,
                )
            )

        # Availability: weekdays always, plus some Saturday cover. Split into
        # two windows so the lunch break is expressed as the gap between them.
        for weekday in (
            Weekday.MONDAY,
            Weekday.TUESDAY,
            Weekday.WEDNESDAY,
            Weekday.THURSDAY,
            Weekday.FRIDAY,
        ):
            session.add(
                Availability(
                    doctor_id=doctor.id,
                    weekday=weekday,
                    start_time=dt.time(CLINIC_OPEN_HOUR, 0),
                    end_time=dt.time(12, 30),
                    effective_from=dt.date(2020, 1, 1),
                    is_active=True,
                )
            )
            session.add(
                Availability(
                    doctor_id=doctor.id,
                    weekday=weekday,
                    start_time=dt.time(13, 30),
                    end_time=dt.time(CLINIC_CLOSE_HOUR, 0),
                    effective_from=dt.date(2020, 1, 1),
                    is_active=True,
                )
            )
        if rng.random() < 0.4:
            session.add(
                Availability(
                    doctor_id=doctor.id,
                    weekday=Weekday.SATURDAY,
                    start_time=dt.time(9, 0),
                    end_time=dt.time(13, 0),
                    effective_from=dt.date(2020, 1, 1),
                    is_active=True,
                )
            )
        doctors.append(doctor)

    session.commit()
    log.info(
        "seeded clinic, %d specialties, %d rooms, %d doctors",
        len(SPECIALTIES),
        6,
        len(doctors),
    )
    return clinic, specialties, doctors


def seed_patients(
    session: Session, fake: Faker, rng: random.Random, n_patients: int
) -> list[tuple[int, float]]:
    """Create patients and return (id, latent no-show offset) pairs.

    The latent offset is the mechanism that makes a patient's history
    predictive of their future. It is never written to the database — only its
    *consequences* are, exactly as in reality, where you observe behaviour and
    must infer the propensity.
    """
    rows = []
    for _ in range(n_patients):
        rows.append(
            {
                "first_name": fake.first_name(),
                "last_name": fake.last_name(),
                "date_of_birth": fake.date_of_birth(minimum_age=1, maximum_age=95),
                "phone": fake.phone_number()[:32],
                "email": fake.unique.email(),
            }
        )
    session.execute(insert(Patient), rows)
    session.commit()

    ids = list(session.execute(select(Patient.id).order_by(Patient.id)).scalars())
    baseline_logit = _logit(PATIENT_PROPENSITY_MEAN)
    out = []
    for pid in ids:
        propensity = rng.betavariate(PATIENT_PROPENSITY_ALPHA, PATIENT_PROPENSITY_BETA)
        propensity = min(max(propensity, 0.01), 0.95)
        out.append((pid, _logit(propensity) - baseline_logit))
    log.info("seeded %d patients", len(out))
    return out


def generate_appointments(
    session: Session,
    rng: random.Random,
    clinic: Clinic,
    specialties: dict[str, Specialty],
    doctors: list[Doctor],
    patients: list[tuple[int, float]],
    start_date: dt.date,
    end_date: dt.date,
    today: dt.date,
    batch_size: int = 2000,
) -> int:
    # Which doctors can serve each specialty, from the junction table.
    doctor_ids_by_specialty: dict[int, list[int]] = {}
    for spec_id, doc_id in session.execute(
        select(doctor_specialty.c.specialty_id, doctor_specialty.c.doctor_id)
    ):
        doctor_ids_by_specialty.setdefault(spec_id, []).append(doc_id)

    calendar = DoctorCalendar()
    seen_patients: set[int] = set()
    spec_by_slug = {s.slug: s for s in SPECIALTIES}

    pending: list[dict] = []
    total = 0
    skipped = 0

    date = start_date
    while date <= end_date:
        weekday = date.isoweekday()
        for slug, spec_row in specialties.items():
            spec = spec_by_slug[slug]
            eligible = doctor_ids_by_specialty.get(spec_row.id, [])
            if not eligible:
                continue
            for hour in range(CLINIC_OPEN_HOUR, CLINIC_CLOSE_HOUR):
                lam = expected_volume(spec, date, hour)
                if lam <= 0:
                    continue
                # Poisson sampling via Knuth's method; lambda is small here.
                n = _poisson(rng, lam)
                for _ in range(n):
                    patient_id, patient_offset = rng.choice(patients)
                    is_new_patient = patient_id not in seen_patients
                    seen_patients.add(patient_id)

                    urgency = sample_urgency(rng)
                    lead_days = sample_lead_days(rng, urgency)
                    duration = sample_duration(rng, spec, is_new_patient)

                    minute = rng.choice([0, 15, 30, 45])
                    start = dt.time(hour, minute)
                    doctor_id = rng.choice(eligible)
                    if not calendar.try_book(doctor_id, date, start, duration):
                        # Try the other eligible doctors before giving up. A
                        # skipped appointment is fine and realistic (the clinic
                        # was full), but silently skipping most of them would
                        # flatten the demand signal, so validate_data.py checks
                        # the skip rate.
                        placed = False
                        for alt in rng.sample(eligible, k=len(eligible)):
                            if calendar.try_book(alt, date, start, duration):
                                doctor_id = alt
                                placed = True
                                break
                        if not placed:
                            skipped += 1
                            continue

                    end_minutes = hour * 60 + minute + duration
                    end = dt.time(end_minutes // 60, end_minutes % 60)

                    booked_date = date - dt.timedelta(days=lead_days)
                    booked_at = dt.datetime.combine(
                        booked_date,
                        dt.time(rng.randrange(8, 18), rng.randrange(0, 60)),
                        tzinfo=dt.UTC,
                    )
                    appt_start_dt = dt.datetime.combine(date, start, tzinfo=dt.UTC)
                    if booked_at > appt_start_dt:  # honours the CHECK constraint
                        booked_at = appt_start_dt - dt.timedelta(hours=1)

                    status = _resolve_status(
                        rng=rng,
                        date=date,
                        today=today,
                        lead_days=lead_days,
                        weekday=weekday,
                        hour=hour,
                        patient_offset=patient_offset,
                        is_new_patient=is_new_patient,
                        urgency=urgency,
                    )

                    pending.append(
                        {
                            "clinic_id": clinic.id,
                            "doctor_id": doctor_id,
                            "patient_id": patient_id,
                            "specialty_id": spec_row.id,
                            "appointment_date": date,
                            "start_time": start,
                            "end_time": end,
                            "booked_at": booked_at,
                            "status": status,
                            "urgency": urgency,
                            "is_new_patient": is_new_patient,
                            "room_id": None,
                        }
                    )
                    if len(pending) >= batch_size:
                        session.execute(insert(Appointment), pending)
                        session.commit()
                        total += len(pending)
                        log.info("inserted %d appointments", total)
                        pending.clear()
        date += dt.timedelta(days=1)

    if pending:
        session.execute(insert(Appointment), pending)
        session.commit()
        total += len(pending)

    log.info("generated %d appointments (%d skipped: clinic full)", total, skipped)
    return total


def _resolve_status(
    *,
    rng: random.Random,
    date: dt.date,
    today: dt.date,
    lead_days: int,
    weekday: int,
    hour: int,
    patient_offset: float,
    is_new_patient: bool,
    urgency: Urgency,
) -> AppointmentStatus:
    """Future appointments are simply scheduled; past ones get an outcome.

    Cancellation is decided first, because a cancelled appointment cannot also
    be a no-show — conflating the two would corrupt the no-show label the
    Phase 3 classifier trains on.
    """
    if date >= today:
        # Some future appointments are already cancelled.
        if rng.random() < cancel_probability(lead_days) * 0.5:
            return AppointmentStatus.CANCELLED
        return AppointmentStatus.SCHEDULED

    if rng.random() < cancel_probability(lead_days):
        return AppointmentStatus.CANCELLED

    p_no_show = no_show_probability(
        lead_days=lead_days,
        weekday=weekday,
        hour=hour,
        patient_offset=patient_offset,
        is_new_patient=is_new_patient,
        urgency=urgency,
    )
    return AppointmentStatus.NO_SHOW if rng.random() < p_no_show else AppointmentStatus.COMPLETED


def _poisson(rng: random.Random, lam: float) -> int:
    """Knuth's algorithm. Fine for the small lambdas used here (< 10)."""
    if lam <= 0:
        return 0
    limit = math.exp(-lam)
    k = 0
    p = 1.0
    while True:
        p *= rng.random()
        if p <= limit:
            return k
        k += 1
        if k > 50:  # guard against pathological lambda
            return k


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--months", type=int, default=12, help="months of history to generate")
    parser.add_argument("--future-days", type=int, default=30, help="days of future bookings")
    parser.add_argument("--doctors", type=int, default=8)
    parser.add_argument("--patients", type=int, default=1500)
    parser.add_argument("--seed", type=int, default=20260821)
    parser.add_argument("--reset", action="store_true", help="truncate existing data first")
    args = parser.parse_args()

    rng = random.Random(args.seed)
    fake = Faker()
    Faker.seed(args.seed)

    today = dt.date.today()
    start_date = today - dt.timedelta(days=30 * args.months)
    end_date = today + dt.timedelta(days=args.future_days)

    engine = create_engine(settings.database_url_sync, future=True)
    with Session(engine) as session:
        if args.reset:
            reset_data(session)

        existing = session.execute(select(Clinic.id)).first()
        if existing and not args.reset:
            log.error("data already present; re-run with --reset to regenerate")
            return 1

        clinic, specialties, doctors = seed_reference_data(session, fake, rng, args.doctors)
        patients = seed_patients(session, fake, rng, args.patients)
        count = generate_appointments(
            session,
            rng,
            clinic,
            specialties,
            doctors,
            patients,
            start_date,
            end_date,
            today,
        )

    log.info("done: %d appointments across %s .. %s", count, start_date, end_date)
    log.info("next step: uv run python scripts/validate_data.py")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
